vich_uploader:
    db_driver: orm

    mappings:
        cover_images:
            uri_prefix: /images/covers
            upload_destination: '%kernel.project_dir%/public/images/covers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        user_photos:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
